/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WaiterForm.java
 *
 * Created on 02.nov.2010, 20:46:42
 */

package gui;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.ListModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import system.*;

/**
 *
 * @author Anders
 */
public class WaiterForm extends javax.swing.JFrame {

    private MainFrame parent;

    /** Creates new form WaiterForm */
    public WaiterForm(MainFrame parent) {
        this.parent = parent;

        initComponents();

        init();
    }

    private void init(){

        try {

            Menu menu = OrderDB.getMenu();

            DefaultListModel mod = new DefaultListModel();

            for (Dish dish : menu.getMenu()){
                mod.addElement(dish);
            }

            menuList.setModel(mod);
            dishOrderList.setModel(new DefaultListModel());
        }
        catch (SQLException e){
            System.out.println(e);
        }
        catch (Exception e){
            System.out.println(e);
        }

        bindTocustomerTextChanged(txtCustomerFirstName);
        bindTocustomerTextChanged(txtCustomerLastName);
        bindTocustomerTextChanged(txtCustomerPhone);
        bindTocustomerTextChanged(txtCustomerAddress);
    }

    private void bindTocustomerTextChanged(final JTextField field){
        field.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                customerTextChanged(field);
            }
            public void removeUpdate(DocumentEvent e) {
                customerTextChanged(field);
            }
            public void changedUpdate(DocumentEvent e) {
                customerTextChanged(field);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupCustomer = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        txtCustomerFirstName = new javax.swing.JTextField();
        txtCustomerLastName = new javax.swing.JTextField();
        txtCustomerPhone = new javax.swing.JTextField();
        txtCustomerAddress = new javax.swing.JTextField();
        checkBoxDelivery = new javax.swing.JCheckBox();
        checkBoxCustomAddress = new javax.swing.JCheckBox();
        txtCustomAddress = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuList = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        btnAddToOrder = new javax.swing.JButton();
        btnRemoveFromOrder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dishOrderList = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        btnGetLastOrder = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();

        popupCustomer.setToolTipText("");
        popupCustomer.setFocusable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Waiter");
        setMinimumSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                WaiterFormClosed(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 75));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 75));

        txtCustomerFirstName.setFont(new java.awt.Font("Tahoma", 0, 14));
        txtCustomerFirstName.setForeground(java.awt.Color.lightGray);
        txtCustomerFirstName.setText("First Name");
        txtCustomerFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCustomerFirstName.setMinimumSize(new java.awt.Dimension(150, 20));
        txtCustomerFirstName.setName("First Name"); // NOI18N
        txtCustomerFirstName.setPreferredSize(new java.awt.Dimension(150, 20));
        txtCustomerFirstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCustomerFieldMouseClicked(evt);
            }
        });
        txtCustomerFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustomerFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerFieldFocusLost(evt);
            }
        });

        txtCustomerLastName.setFont(txtCustomerFirstName.getFont());
        txtCustomerLastName.setForeground(txtCustomerFirstName.getForeground());
        txtCustomerLastName.setText("Last Name");
        txtCustomerLastName.setBorder(txtCustomerFirstName.getBorder());
        txtCustomerLastName.setMinimumSize(new java.awt.Dimension(150, 20));
        txtCustomerLastName.setName("Last Name"); // NOI18N
        txtCustomerLastName.setPreferredSize(new java.awt.Dimension(150, 20));
        txtCustomerLastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCustomerFieldMouseClicked(evt);
            }
        });
        txtCustomerLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustomerFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerFieldFocusLost(evt);
            }
        });

        txtCustomerPhone.setFont(txtCustomerFirstName.getFont());
        txtCustomerPhone.setForeground(txtCustomerFirstName.getForeground());
        txtCustomerPhone.setText("Phone Number");
        txtCustomerPhone.setBorder(txtCustomerFirstName.getBorder());
        txtCustomerPhone.setMinimumSize(new java.awt.Dimension(150, 20));
        txtCustomerPhone.setName("Phone Number"); // NOI18N
        txtCustomerPhone.setPreferredSize(new java.awt.Dimension(150, 20));
        txtCustomerPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCustomerFieldMouseClicked(evt);
            }
        });
        txtCustomerPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustomerFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerFieldFocusLost(evt);
            }
        });

        txtCustomerAddress.setFont(txtCustomerFirstName.getFont());
        txtCustomerAddress.setForeground(txtCustomerFirstName.getForeground());
        txtCustomerAddress.setText("Address");
        txtCustomerAddress.setBorder(txtCustomerFirstName.getBorder());
        txtCustomerAddress.setName("Address"); // NOI18N
        txtCustomerAddress.setPreferredSize(new java.awt.Dimension(105, 20));
        txtCustomerAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCustomerFieldMouseClicked(evt);
            }
        });
        txtCustomerAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustomerFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerFieldFocusLost(evt);
            }
        });

        checkBoxDelivery.setFont(txtCustomerFirstName.getFont());
        checkBoxDelivery.setText("Delivery");
        checkBoxDelivery.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxDeliveryStateChanged(evt);
            }
        });

        checkBoxCustomAddress.setFont(txtCustomerFirstName.getFont());
        checkBoxCustomAddress.setText("Custom address");
        checkBoxCustomAddress.setEnabled(false);
        checkBoxCustomAddress.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkBoxCustomAddressEnabledChanged(evt);
            }
        });
        checkBoxCustomAddress.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxCustomAddressStateChanged(evt);
            }
        });

        txtCustomAddress.setFont(txtCustomerFirstName.getFont());
        txtCustomAddress.setForeground(java.awt.Color.lightGray);
        txtCustomAddress.setText("Custom Address");
        txtCustomAddress.setBorder(txtCustomerFirstName.getBorder());
        txtCustomAddress.setEnabled(false);
        txtCustomAddress.setName("Custom Address"); // NOI18N
        txtCustomAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustomerFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(checkBoxDelivery)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxCustomAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCustomerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxDelivery)
                    .addComponent(checkBoxCustomAddress)
                    .addComponent(txtCustomAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        menuList.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        menuList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuList.setPreferredSize(new java.awt.Dimension(200, 80));
        jScrollPane1.setViewportView(menuList);

        jPanel2.add(jScrollPane1);

        jPanel4.setMaximumSize(new java.awt.Dimension(70, 32767));
        jPanel4.setMinimumSize(new java.awt.Dimension(70, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(70, 183));

        btnAddToOrder.setText("=>");
        btnAddToOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToOrderActionPerformed(evt);
            }
        });

        btnRemoveFromOrder.setText("<=");
        btnRemoveFromOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFromOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAddToOrder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveFromOrder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnAddToOrder)
                .addGap(69, 69, 69)
                .addComponent(btnRemoveFromOrder)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);

        dishOrderList.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        dishOrderList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item1", "Item2" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        dishOrderList.setPreferredSize(new java.awt.Dimension(200, 80));
        jScrollPane2.setViewportView(dishOrderList);

        jPanel2.add(jScrollPane2);

        getContentPane().add(jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 45));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 45));

        btnGetLastOrder.setText("Get last order");

        btnPlaceOrder.setText("Place order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGetLastOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 624, Short.MAX_VALUE)
                .addComponent(btnPlaceOrder)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGetLastOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(btnPlaceOrder))
                .addContainerGap())
        );

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WaiterFormClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_WaiterFormClosed
        parent.setVisible(true);
    }//GEN-LAST:event_WaiterFormClosed

    private void txtCustomerFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerFieldFocusGained
        JTextField focusedTextField = (JTextField)evt.getSource();

        if (focusedTextField.getText().equals(focusedTextField.getName())){
            focusedTextField.setText("");
            focusedTextField.setForeground(Color.black);
        }

        customerTextChanged(focusedTextField);
    }//GEN-LAST:event_txtCustomerFieldFocusGained

    private void txtCustomerFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerFieldFocusLost
        JTextField focusedTextField = (JTextField)evt.getSource();

        if (focusedTextField.getText().equals("")){
            focusedTextField.setText(focusedTextField.getName());
            focusedTextField.setForeground(Color.lightGray);
        }

        popupCustomer.setVisible(false);
    }//GEN-LAST:event_txtCustomerFieldFocusLost

    private void checkBoxDeliveryStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxDeliveryStateChanged
        JCheckBox check = (JCheckBox)evt.getSource();

        if (check.isSelected()){
            checkBoxCustomAddress.setEnabled(true);
        }
        else {
            checkBoxCustomAddress.setEnabled(false);
            txtCustomAddress.setEnabled(false);
        }
    }//GEN-LAST:event_checkBoxDeliveryStateChanged

    private void checkBoxCustomAddressStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxCustomAddressStateChanged
        JCheckBox check = (JCheckBox)evt.getSource();

        if (check.isEnabled()) {
            if (check.isSelected()) {
                txtCustomAddress.setEnabled(true);
            } else {
                txtCustomAddress.setEnabled(false);
            }
        }
    }//GEN-LAST:event_checkBoxCustomAddressStateChanged

    private void checkBoxCustomAddressEnabledChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkBoxCustomAddressEnabledChanged
        JCheckBox check = (JCheckBox)evt.getSource();

        if (check.isEnabled()) {
            if (check.isSelected()) {
                txtCustomAddress.setEnabled(true);
            } else {
                txtCustomAddress.setEnabled(false);
            }
        }
    }//GEN-LAST:event_checkBoxCustomAddressEnabledChanged

    private void btnAddToOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToOrderActionPerformed
        if (!menuList.isSelectionEmpty()){
            ListModel model = dishOrderList.getModel();

            DefaultListModel mod = convertToDefaultListModel(model);

            Dish selectedDish = (Dish)menuList.getSelectedValue();

            DishOrder toBeAdded = new DishOrder(selectedDish, 1, ""); // TODO: read comment from textBox

            mod.addElement(toBeAdded);

            dishOrderList.setModel(mod);
        }
    }//GEN-LAST:event_btnAddToOrderActionPerformed

    private DefaultListModel convertToDefaultListModel(ListModel list){
        DefaultListModel mod = new DefaultListModel();

        for (int i = 0; i < list.getSize(); ++i) {
            mod.addElement(list.getElementAt(i));
        }

        return mod;
    }

    private void customerTextChanged(JTextField invoker){
        if (invoker.hasFocus() && invoker.getText().length() > 0){
            try {
                ArrayList<Customer> customers = OrderDB.getAllCustomers(); // TODO: search for customers in the database

                if (customers.size() > 0){
                    popupCustomer.removeAll();

                    for (Customer cust : customers){
                        JMenuItem item = new JMenuItem(cust.toString());
                        item.setName(cust.id + ""); // TODO: maybe a cleaner way to do this ?
                        popupCustomer.add(item);
                    }

                    popupCustomer.setVisible(false);
                    popupCustomer.show(txtCustomerFirstName, 0, 20);
                    //invoker.requestFocusInWindow();
                }
            }
            catch (SQLException e){

            }
        }
    }

    private void btnRemoveFromOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFromOrderActionPerformed
        if (!dishOrderList.isSelectionEmpty()) {
            ListModel list = dishOrderList.getModel();

            DefaultListModel mod = convertToDefaultListModel(list);

            mod.removeElementAt(dishOrderList.getSelectedIndex());

            dishOrderList.setModel(mod);
        }
    }//GEN-LAST:event_btnRemoveFromOrderActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        ListModel list = dishOrderList.getModel();
        
        if (list.getSize() > 0){
            ArrayList<DishOrder> listOrders = new ArrayList<DishOrder>();

            for (int i = 0; i < list.getSize(); i++){
                dishOrderList.setSelectedIndex(i);
                listOrders.add((DishOrder)dishOrderList.getSelectedValue());
            }

            ArrayList<DishOrder> mergedListOrders = new ArrayList<DishOrder>();

            mainLoop: for (DishOrder order : listOrders){
                for (DishOrder compareOrder : mergedListOrders){
                    if (order.dishID == compareOrder.dishID &&
                            order.comments.equals(compareOrder.comments)){
                        compareOrder.amount++;
                        continue mainLoop;
                    }
                }
                mergedListOrders.add(order);
            }

            for (DishOrder tmp : mergedListOrders){
                System.out.println(tmp);
            }
        }
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void txtCustomerFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCustomerFieldMouseClicked
        JTextField focusedTextField = (JTextField)evt.getSource();
        customerTextChanged(focusedTextField);
    }//GEN-LAST:event_txtCustomerFieldMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToOrder;
    private javax.swing.JButton btnGetLastOrder;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRemoveFromOrder;
    private javax.swing.JCheckBox checkBoxCustomAddress;
    private javax.swing.JCheckBox checkBoxDelivery;
    private javax.swing.JList dishOrderList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList menuList;
    private javax.swing.JPopupMenu popupCustomer;
    private javax.swing.JTextField txtCustomAddress;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerFirstName;
    private javax.swing.JTextField txtCustomerLastName;
    private javax.swing.JTextField txtCustomerPhone;
    // End of variables declaration//GEN-END:variables

}
