/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 02.nov.2010, 20:13:20
 */

package gui;

import javax.swing.UIManager;
import system.*;

/**
 *
 * @author Anders
 */
public class MainFrame extends javax.swing.JFrame implements FormListener {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();


        try {
            // Initialize DB
            OrderDB.initializeDB(testing.DBInfo.username, testing.DBInfo.password, "jdbc:mysql://mysql.stud.ntnu.no/andereie_itgrupp");
        }
        catch (Exception e){
            System.out.println(e);
        }
    }

    public void tell(int signal) {
        if (signal == 0){
            // Reload the waiter form
            new WaiterForm(this).setVisible(true);
            this.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnSelectUserWaiter = new javax.swing.JButton();
        btnSelectUserChef = new javax.swing.JButton();
        btnSelectUserAdmin = new javax.swing.JButton();
        btnSelectUserDriver = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("MainFrame"); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setPreferredSize(new java.awt.Dimension(200, 600));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);

        jPanel1.setMaximumSize(new java.awt.Dimension(235, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(235, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(235, 600));

        btnSelectUserWaiter.setFont(new java.awt.Font("Tahoma", 1, 36));
        btnSelectUserWaiter.setText("Waiter");
        btnSelectUserWaiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectUserWaiterActionPerformed(evt);
            }
        });

        btnSelectUserChef.setFont(btnSelectUserWaiter.getFont());
        btnSelectUserChef.setText("Chef");
        btnSelectUserChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectUserChefActionPerformed(evt);
            }
        });

        btnSelectUserAdmin.setFont(btnSelectUserWaiter.getFont());
        btnSelectUserAdmin.setText("Admin");
        btnSelectUserAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectUserAdminActionPerformed(evt);
            }
        });

        btnSelectUserDriver.setFont(btnSelectUserWaiter.getFont());
        btnSelectUserDriver.setText("Driver");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSelectUserAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSelectUserChef, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSelectUserWaiter, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSelectUserDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addComponent(btnSelectUserWaiter, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnSelectUserChef, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnSelectUserDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnSelectUserAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(196, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);

        jPanel3.setPreferredSize(new java.awt.Dimension(200, 600));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectUserWaiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectUserWaiterActionPerformed
        new WaiterForm(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSelectUserWaiterActionPerformed

    private void btnSelectUserChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectUserChefActionPerformed
        new CookFrame(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSelectUserChefActionPerformed

    private void btnSelectUserAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectUserAdminActionPerformed
        new AdminPanelSelecter(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSelectUserAdminActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {
                }
                
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectUserAdmin;
    private javax.swing.JButton btnSelectUserChef;
    private javax.swing.JButton btnSelectUserDriver;
    private javax.swing.JButton btnSelectUserWaiter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
